name: test

on:
  push: 
    branches: [ main ]
  pull_request: 
    branches: [ main ]

jobs:
  test:
    runs-on: self-hosted
    env:
      NUMBER_OF_COMPUTE_NODES: 3
    steps: 
      - name: checkout code
        uses: actions/checkout@v2.3.4
        timeout-minutes: 10
#      - name: Kubernetes info
#        timeout-minutes: 5
#        run: |
#          kubectl cluster-info
#          kubectl get pods -n kube-system
#          cat ~/.kube/config
#          ls -lah ~/.kube/config
#          cd ~/.kube/
#          pwd
      - name: workspace path
        run: |
          echo -e "\033[35m home path is $HOME \033[0m"
          echo -e "\033[35m workspace path is `pwd` \033[0m"
      - name: install basic environment tool
        run: sudo chmod +x ./test/hack/install-basic-environment-tool.sh && ./test/hack/install-basic-environment-tool.sh
      - name: install kind and kubectl
        run: sudo chmod +x ./test/hack/install-test-tool.sh && source ./test/hack/install-test-tool.sh
      - name: setup kind cluster
        run: sudo chmod +x ./test/hack/setup-kind-cluster.sh && ./test/hack/setup-kind-cluster.sh --number-of-compute $NUMBER_OF_COMPUTE_NODES